### ISSUE TITLE
Add abstract methods in ConsumerActor for Tenant and Lessor methods

### ISSUE THREAD

**Issue by robgc** [bjjr/d08#6]

**Comment by javsanpar** [comment]
La llamada del contructor de ConsumerActor
```java
new ConsumerActor();
```
devuelve el siguiente error: **Cannot instantiate the type ConsumerActor**

**Comment by javiersantos** [comment]
Solo necesitas inicializar el constructor de `Tenant` o `Lessor` y añadir las propiedades de `ConsumerActor` y `Actor`.

```Java
Tenant tenant = new Tenant();
tenant.setCreditCard(...); // Propiedad de ConsumerActor
tenant.setName(""); // Propiedad de Actor
...
```

Por lo que sería crear un método que dado un ConsumerActor lo rellene con sus propiedades. Ej:

```Java
public void setConsumerActorProperties(ConsumerActor ca) {
    ca.setCreditCard(...);
}
```

**Comment by robgc** [comment]
Se ha añadido el método _setConsumerActorProperties_ en la clase __ConsumerActor__. En la rama t1 se encuentra este cambio.

https://github.com/bjjr/d08/commit/828299758dd855a48c9e282fd9908edbde3bc3ad cierra este issue.
